#!/bin/bash

cat <<EOF

Owncloud $(cat /usr/share/owncloud/version.php | grep VersionString | cut -d\' -f2) is installed in /usr/share/owncloud.
EOF

# FIXME: check if owncloud is installed
cat <<EOF
MySQL is configured for user root with password $(cat /root/.my.cnf | grep password | awk '{print $3}').
To continue the installation, open http://$(/usr/local/bin/oc-metadata PUBLIC_IP_ADDRESS)/owncloud/ in your browser.
EOF

cat <<EOF
You can hide this message on the next connection by deleting the $0 file.
EOF
