#!/bin/bash

. ../ubuntu-utopic/build --source-only

DISTRIB=wordpress
NAME="rootfs-$ARCH-$DISTRIB-$VERSION"
PKGS_INCLUDE="$PKGS_INCLUDE,nginx,mysql-server,php5,php5-cli,php5-fpm,php5-mysql,php5-gd,php5-mcrypt,pwgen"

wordpress_patch_image() {
    # Inherits parent image
    ubuntu_utopic_patch_image

    # Install Wordpress
    do_in_target "wget -qO latest.tar.gz http://wordpress.org/latest.tar.gz"
    do_in_target "tar -xzvf latest.tar.gz"
    do_in_target "mv wordpress /var/www"
    do_in_target "cp /var/www/wp-config-sample.php /var/www/wp-config.php"
    do_in_target "rm -f latest.tar.gz"

    # Patches
    patch_target app-wordpress/patches

    # Configures nginx
    do_in_target "ln -sf /etc/nginx/site-available/wordpress /etc/nginx/site-enabled/wordpress"
    do_in_target "rm -f /etc/nginx/site-enabled/default"

}
patch_image() {
    wordpress_patch_image
}

if [ "${1}" != "--source-only" ]; then
    cli $@
fi

