language: bash

script:
    - for file in images/*/build; do bash -n $file; done
    - for file in images/*/Dockerfile; do bash -n $file; done
    - for file in images/*/Makefile; do make -n -C $(dirname $file); done