#!/bin/bash

. ../ubuntu-trusty/build --source-only

PKGS_INCLUDE="$PKGS_INCLUDE,iotop,iperf,ethstatus,traceroute,tcpdump,busybox,htop,socat,lsof,parted,lvm2,partimage,memtester,rsync"
NAME=${NAME:-"rootfs-$ARCH-rescue"}

rescue_patch_image() {
    # Inherits parent patch_image
    ubuntu_trusty_patch_image

    # Rescue patches
    patch_target rescue/patches
}
patch_image() {
    rescue_patch_image
}

if [ "${1}" != "--source-only" ]; then
    cli $@
fi
