NAME =		ocs-ubuntu
VERSION =	utopic
IS_LATEST =	1
TITLE =		Ubuntu Utopic
DESCRIPTION =	Ubuntu Utopic (14.10)
SOURCE_URL =	https://github.com/online-labs/image-builder/tree/master/distrib-ubuntu-utopic

include ../docker-rules.mk
