NAME =		ocs-distrib-ubuntu
VERSION =	vivid
IS_LATEST =	1
TITLE =		Ubuntu Vivid
DESCRIPTION =	Ubuntu Vivid (15.04)
SOURCE_URL =	https://github.com/online-labs/image-builder/tree/master/distrib-ubuntu-vivid

include ../docker-rules.mk
