NAME =		ocs-distrib-debian
VERSION =	wheezy
IS_LATEST =	1
TITLE =		Debian
DESCRIPTION =	Debian Wheezy (7.7)
SOURCE_URL =	https://github.com/online-labs/image-builder/tree/master/distrib-debian-wheezy

include ../docker-rules.mk
