#!/bin/bash

. ../docker/build --source-only

DISTRIB=tryit-docker
NAME="rootfs-$ARCH-$DISTRIB-$VERSION"
PKGS_INCLUDE="$PKGS_INCLUDE,nodejs,npm,make,g++"

patch_image() {
    docker_patch_image
    patch_target tryit-docker/patches

    # Install nodejs
    # curl -sL https://deb.nodesource.com/setup | do_in_target bash -
    # do_in_target apt-get -y install nodejs

    # Create node binary
    ln -s /usr/bin/nodejs "$TARGET"/usr/bin/node

    # Install tty.js
    do_in_target npm install -g tty.js
    sudo ln -s ../lib/node_modules/tty.js/bin/tty.js "$TARGET"/usr/bin/

    # Create ubuntu user with sudo access
    do_in_target useradd -G sudo -m ubuntu
    # Remove password for sudo
    sudo sed -i '/sudo/s/ALL)/ALL) NOPASSWD:/' "$TARGET"/etc/sudoers
}

if [ "${1}" != "--source-only" ]; then
    cli $@
fi
