#!/bin/bash

. ../ubuntu-trusty/build --source-only

DISTRIB=owncloud
NAME="rootfs-$ARCH-$DISTRIB-$VERSION"
PKGS_INCLUDE="$PKGS_INCLUDE,mysql-server,owncloud"

owncloud_patch_image() {
    # Finish install of owncloud
    do_in_target "apt-get update"
    do_in_target "apt-get -f install"

    # Inherits parent image
    ubuntu_trusty_patch_image

    # Patch image
    patch_target app-owncloud/patches

    # Configures apache/php
    do_in_target "a2enmod rewrite"
}
patch_image() {
    owncloud_patch_image
}

if [ "${1}" != "--source-only" ]; then
    cli $@
fi
