#! /bin/sh

### BEGIN INIT INFO
# Provides:		sshkeys
# Required-Start:	$remote_fs $sshd
# Required-Stop:	$remote_fs $sshd
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description:	SSH Keys
### END INIT INFO

set -e

sshkey_start() {
    if [ ! -f /etc/ssh/ssh_host_rsa_key ]
    then
        ssh-keygen -t rsa -b 4096 -N '' -f /etc/ssh/ssh_host_rsa_key
        ssh-keygen -t dsa -N '' -f /etc/ssh/ssh_host_dsa_key
        ssh-keygen -t ecdsa -N '' -f /etc/ssh/ssh_host_ecdsa_key
        ssh-keygen -t ed25519 -N '' -f /etc/ssh/ssh_host_ed25519_key
    fi

    if [ ! -f /root/.ssh/authorized_keys ]
    then
        mkdir -p /root/.ssh/
    fi

    /usr/local/bin/oc-metadata | grep SSH_PUBLIC_KEYS_.*_KEY | cut -d'=' -f 2- | tr -d \' > /root/.ssh/authorized_keys
}


export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	sshkey_start
	;;
  reload|force-reload)
	sshkey_start
	;;
  restart)
	sshkey_start
	;;
  *)
	log_action_msg "Usage: /etc/init.d/ssh-keys {start|restart}" || true
	exit 1
esac

exit 0
