#!/bin/sh
# Filename:     /etc/dhcp/dhclient-exit-hooks.d/hostname
# Purpose:      Used by dhclient-script to set the hostname of the system
#               to match the DNS information for the host as provided by
#               DHCP.
#

echo dhclient-exit-hooks.d/hostname: Dynamic IP address = $new_ip_address
echo dhclient-exit-hooks.d/hostname: Dynamic host name = $new_host_name

metadata_host_name=$(/usr/local/bin/oc-metadata HOSTNAME)
if [ "x$metadata_host_name" != "x" ]; then
    echo dhclient-exit-hooks.d/hostname: Metadata host name = $metadata_host_name
    new_host_name="$metadata_host_name"

fi

echo $new_host_name > /etc/hostname
sed "/^127.0.1.1[ \t].*$/ s/.*$/127.0.1.1\t$new_host_name/" -i /etc/hosts
sed "/^127.0.0.1[ \t]localhost/ s/localhost.*$/localhost $new_host_name/" -i /etc/hosts
hostname $new_host_name
echo dhclient-exit-hooks.d/hostname: Dynamic Hostname = $new_host_name

