#!/bin/bash

. ../lib.sh  # Include library

# Image
DISTRIB="fedora"
ARCH=${ARCH:-"armhf"}
TARGET=${TARGET:-"rootfs-target"}
CLEAN_PATHS="/root/.bash_history /root/.history /etc/resolv.conf /etc/hostname /etc/ssh/*_key* /var/log/bootstrap.log"
PATCHES_DIR=patches  # without trailing slash
PKGS_INCLUDE=${PKGS_INCLUDE:-"ca-certificates,cron,curl,iptables,iputils-ping,isc-dhcp-client,less,man-db,nano,nbd-client,net-tools,ntp,ntpdate,rsyslog,ssh,sudo,wget,whiptail,xnbd-client"}
VERSION=${VERSION:-"20"}


# Required
NAME=${NAME:-"rootfs-$ARCH-$DISTRIB-$VERSION"}
build_image() {
    if [ ! -f sda.raw ]; then
	if [ ! -f sda.raw.xz ]; then
	    wget -O sda.raw.xz \
		http://mirror.easyspeedy.com/fedora/releases/$VERSION/Images/armhfp/Fedora-Minimal-armhfp-$VERSION-1-sda.raw.xz
	fi
	unxz sda.raw.xz
    fi
    umount $NBD_DEVICE
    dd if=sda.raw of=$NBD_DEVICE bs=1M
    mount $NBD_DEVICE $TARGET
}

patch_image() {
    # FIXME: patch_target $PATCHES_DIR
    echo
}

upgrade_image() {
    # FIXME: upgrade security packages
    echo
}

clean_image() {
    # FIXME: clean package achives
    clean_target $CLEAN_PATHS
    # FIXME: reload package index
}


if [ "${1}" != "--source-only" ]; then
    cli $@
fi
