NAME =		ocs-ubuntu
VERSION =	trusty
IS_LATEST =	0
TITLE =		Ubuntu Trusty
DESCRIPTION =	Ubuntu Trusty (14.04LTS)
SOURCE_URL =	https://github.com/online-labs/image-builder/tree/master/distrib-ubuntu-trusty

include ../docker-rules.mk
