#!/bin/bash

. ../ubuntu-trusty/build --source-only

VERSION="utopic"
NAME="rootfs-$ARCH-$DISTRIB-$VERSION"
SCRIPT="/usr/share/debootstrap/scripts/trusty"

ubuntu_utopic_patch_image() {
    ubuntu_trusty_patch_image

    # Override ubuntu-trusty files with ubuntu-utopic files
    patch_target ubuntu-utopic/patches
}
patch_image() {
    ubuntu_utopic_patch_image
}

if [ "${1}" != "--source-only" ]; then
    cli $@
fi
