#!/bin/bash

# This script will clean the rootfs for a normal usage.
# Globally, it will cancel effects of the builder-enter script.
# It also clean rootfs to make image "forkable"

set -e

# unprevent init scripts from running during install/update
dpkg-divert --remove /sbin/initctl
rm /usr/sbin/policy-rc.d /sbin/initctl

# remove potentially existing docker aptitude tuning
rm -f /etc/apt/apt.conf.d/docker-*
rm -f /.dockerenv /.dockerinit

# remove ssh host keys so they are regenerated on first boot
rm -f /etc/ssh/*_key*

# clean history
rm -f /root/.history /root/.bash_history

# clean aptitude
rm -f /var/cache/apt/*.bin /var/cache/apt/archives/partial/*.deb \
      /var/cache/apt/archives/*.deb

# clean debootstrap
rm -f /var/log/bootstrap.log

# Update locate cache
updatedb || true
