#!/bin/bash

. ../lib.sh  # Include library

# Image
DISTRIB="debian"
TARGET=${TARGET:-"rootfs-target"}
CLEAN_PATHS="/root/.bash_history /root/.history /etc/resolv.conf /etc/hostname /etc/ssh/*_key* /var/log/bootstrap.log"
PATCHES_DIR=patches  # without trailing slash

# Debootstrap configuration
ARCH=${ARCH:-"armhf"}
VARIANT=${VARIANT:-"minbase"}
COMPONENTS=${COMPONENTS:-"main"}
PKGS_INCLUDE=${PKGS_INCLUDE:-"ca-certificates,cron,curl,iptables,iputils-ping,isc-dhcp-client,less,man-db,nano,nbd-client,net-tools,ntp,ntpdate,rsyslog,ssh,sudo,wget,whiptail,xnbd-client,locales"}
MIRROR=${MIRROR:-"http://ftp.fr.debian.org/debian/"}
VERSION=${VERSION:-"wheezy"}
SCRIPT=""


# Required
NAME=${NAME:-"rootfs-$ARCH-$DISTRIB-$VERSION"}
build_image() {
    require_debootstrap
    clean_workspace
    debootstrap
    secondstage
    upgrade_debs
}

patch_image() {
    patch_target $PATCHES_DIR

    # locales
    do_in_target locale-gen

    echo 'echo "root:toortmptmp" | chpasswd' | do_in_target

    # hack to use standard initrd
    sudo ln -s /usr/lib/systemd/systemd "$TARGET/sbin/init"

    clean_target $CLEAN_PATHS
}


cli $@
