#!/bin/bash

. ../lib.sh  # Include library

# Image
DISTRIB="ubuntu"
TARGET=${TARGET:-"rootfs-target"}
CLEAN_PATHS="/root/.bash_history /root/.history /etc/resolv.conf /etc/hostname /etc/ssh/*_key* /var/log/bootstrap.log"
PATCHES_DIR=patches  # without trailing slash

# Debootstrap configuration
ARCH=${ARCH:-"armhf"}
VARIANT=${VARIANT:-"minbase"}
COMPONENTS=${COMPONENTS:-"main,universe"}
PKGS_INCLUDE=${PKGS_INCLUDE:-"ca-certificates,cron,curl,iptables,iputils-ping,isc-dhcp-client,less,man-db,nano,nbd-client,net-tools,ntp,ntpdate,rsyslog,ssh,sudo,wget,whiptail,xnbd-client"}
MIRROR=${MIRROR:-"http://mirror.cloud.online.net/ubuntu-ports/"}
VERSION=${VERSION:-"trusty"}
SCRIPT=""


# Required
NAME=${NAME:-"rootfs-$ARCH-$DISTRIB-$VERSION"}
build_image() {
    require_debootstrap
    clean_workspace
    debootstrap
    secondstage
}

patch_image() {
    patch_target $PATCHES_DIR

    # locales
    do_in_target locale-gen en_US.UTF-8
    do_in_target locale-gen fr_FR.UTF-8
    do_in_target dpkg-reconfigure locales
}

upgrade_image() {
    upgrade_debs
}

clean_image() {
    do_in_target apt-get clean
    clean_target $CLEAN_PATHS
    do_in_target apt-get update
}


if [ "${1}" != "--source-only" ]; then
    cli $@
fi
