#!/bin/bash

. ../ubuntu-utopic/build --source-only

DISTRIB=docker
NAME="rootfs-$ARCH-$DISTRIB-$VERSION"
SCRIPT="/usr/share/debootstrap/scripts/trusty"
PKGS_INCLUDE="$PKGS_INCLUDE,docker.io,bridge-utils"

docker_patch_image() {
    ubuntu_utopic_patch_image
    patch_target docker/patches
}
patch_image() {
    docker_patch_image
}

if [ "${1}" != "--source-only" ]; then
    cli $@
fi
