#!/bin/bash

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi


[ -r /etc/ocs-release ] && . /etc/ocs-release

METADATA=$(/usr/local/bin/oc-metadata)

metadata() {
  key=$1
  echo "$METADATA" | grep "^$key=" | cut -d= -f2 | sed "s/^['\"]//;s/['\"]$//"
}

volume_metadata() {
  device=$1
  key=$2
  metadata VOLUMES_${device}_${key}
}

INTERNAL_IP=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')

cat<<EOF

Welcome on $IMAGE_DESCRIPTION on Online Labs' C1.

 * Kernel:           $(uname -o) $(uname -r) $(uname -m)
 * Distribution:     $IMAGE_DESCRIPTION ($IMAGE_RELEASE) on $DISTRIB_DESCRIPTION
 * Internal ip:      $INTERNAL_IP
 * External ip:      $(metadata PUBLIC_IP_ADDRESS)
EOF

for i in {0..16}; do
  metadata VOLUMES_${i} | grep " " >/dev/null || continue

  SIZE=$(( $(volume_metadata $i SIZE) / 1000 / 1000 / 1000 ))G
  echo " * Disk /dev/nbd${i}:   $(volume_metadata $i NAME) ($(volume_metadata $i VOLUME_TYPE) ${SIZE})"
done

lsmod | grep nolp >/dev/null && \
	echo " * NOLP.ko module:   Running"

echo " * Uptime:          $(/usr/bin/uptime)"

cat<<EOF

Links
 * Documentation:    $IMAGE_DOC_URL
 * Community:        $IMAGE_HELP_URL
 * Image source:     $IMAGE_SOURCE_URL
EOF
