#!/bin/bash

. ../ubuntu-utopic/build --source-only

DISTRIB=pydio
NAME="rootfs-$ARCH-$DISTRIB-$VERSION"
PKGS_INCLUDE="$PKGS_INCLUDE,libapache2-mod-php5,php5-cgi,php5,apache2"

pydio_patch_image() {
    ubuntu_utopic_patch_image
    
    # patch_target app-pydio/patches
}
patch_image() {
    pydio_patch_image
    do_in_target wget -qO /tmp http://dl.ajaxplorer.info/repos/apt/pool/main/p/pydio/pydio_5.3.3_all.deb
    do_in_target dpkg -i /tmp/pydio*.deb
    do_in_target /usr/share/doc/pydio/apache2.sample.conf /etc/apache2/sites-enabled/pydio.conf
    do_in_target ln -sf /etc/php5/mods-available/mcrypt.ini /etc/php5/apache2/conf.d/
}

if [ "${1}" != "--source-only" ]; then
    cli $@
fi
