#!/bin/bash

. ../ubuntu-utopic/build --source-only

DISTRIB=pydio
NAME="rootfs-$ARCH-$DISTRIB-$VERSION"
PKGS_INCLUDE="$PKGS_INCLUDE,libapache2-mod-php5,php5-cgi,php5,apache2,php5-gd,php5-mcrypt,php5-cli,php5-mysqlnd,pwgen,php5-curl,mysql-server"

pydio_patch_image() {
    # Inherits parent image
    ubuntu_utopic_patch_image

    # Install Pydio
    do_in_target "wget -qO /tmp/pydio.deb http://dl.ajaxplorer.info/repos/apt/pool/main/p/pydio/pydio_5.3.3_all.deb"
    do_in_target "dpkg -i /tmp/pydio.deb"
    do_in_target "rm -f /tmp/pydio.deb"

    # Patches
    patch_target app-pydio/patches

    # Configures apache/php
    do_in_target "a2enmod rewrite"
    do_in_target "ln -sf /usr/share/doc/pydio/apache2.sample.conf /etc/apache2/sites-enabled/pydio.conf"
    do_in_target "ln -sf /etc/php5/mods-available/mcrypt.ini /etc/php5/apache2/conf.d/"

    # Pydio dependencies
    do_in_target "cd /usr/share/pydio && curl -sS https://getcomposer.org/installer | php"
    do_in_target "cd /usr/share/pydio && php composer.phar install"
    do_in_target "wget -qO /usr/share/pydio/aws.phar https://github.com/aws/aws-sdk-php/releases/download/2.7.2/aws.phar"
}
patch_image() {
    pydio_patch_image
}

if [ "${1}" != "--source-only" ]; then
    cli $@
fi
